# Generated by Django 4.0 on 2023-12-07 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('resubmission_requested', 'Resubmission_Requested'), ('graded', 'Graded')], default='submitted', max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='aula.material'),
        ),
    ]
