# Generated by Django 4.0 on 2023-11-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0004_alter_submission_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3, null=True),
        ),
    ]
